[package]
name = "scd30pi"
version = "1.0.0"
authors = ["Crispin Tschirky <ct@fhr.ch>"]
edition = "2024"
description = "Interfaces the SCD30 i2c CO2, temperature and humidity sensor from Sensirion for Raspberry Pi"
repository = "https://github.com/crisobal/scd30pi"
readme = "Readme.md"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["raspberry", "co2", "scd30", "i2c"]

[dependencies]
rppal = {  version="0.22.1", features = ["embedded-hal"] }
log = "0.4.29"
